### ISSUE TITLE
Fisherman?

### ISSUE THREAD

**Issue by ghost** [amio/fish-theme-eden#1]
Hi @amio, are you familiar with fisherman?

https://github.com/fisherman/fisherman

<img width="696" alt="screen shot 2016-04-26 at 11 52 26 pm" src="https://cloud.githubusercontent.com/assets/8317250/14822510/f47b66f4-0c09-11e6-9eab-57904db4f308.png">

**Comment by amio** [comment]
Yea, sure, I was think about make a theme for fisher but didn't find out a tutorial or spec,
for now omf has a more convenient helper for making theme.

I'm planing to add instructions about installing with fisher or fin after the theme was stable.

**Comment by ghost** [comment]
Hey @amio, yeah, I wrote that helper :)

Anyway, in fisherman we are taking a more lightweight approach, but here is a template https://github.com/fisherman/prompt-template

**Comment by amio** [comment]
Ooops I missed it :P

**Comment by amio** [comment]
BTW, will this format fits fin?

**Comment by ghost** [comment]
@amio fin and fisherman merged and now it's just fisherman 2.0 :)

**Comment by amio** [comment]
⚡ 👍

**Comment by amio** [comment]
I'll look into it

**Comment by ghost** [comment]
@amio thanks. btw fin is now a new project https://github.com/fisherman/fin

are you also node dev?

**Comment by amio** [comment]
Yea, I was beginning to wonder why fin's description became "node version manager"
